config/routes.rb
Sebitmin::Application.routes.draw do
  devise_for :admins
  resources :photos
  
  match "projects/:id/update_cover_photo" => "projects#update_cover_photo"
  resources :projects do
    resources :photos
  end

  root :to => 'projects#index'
  get "info/about_me"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :photos, :as => :imageable
  belongs_to :cover_photo, :class_name => "Photo"
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include Controllers::Helper

  # GET /projects
  # GET /projects.json
  def index
    project_type = params.delete(:project_type)
    if project_type.nil?
      @projects = Project.all
      history_path = "/"
    else
      @projects = Project.find(:all, :conditions => { :project_type => project_type.to_i })
      history_path = "/?project_type=#{project_type}"
    end
    
    respond_to_ajax_new(:allow_html => true, :history_path => history_path)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    
    collect_result_new
    respond_to_ajax_new(:html_action => "replace_slow", :allow_html => true)
    if @request_type == :html
      params[:action] = "index"
      index
    end
    flush_result_new
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, :notice => 'Project was successfully created.' }
        format.json { render :json => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, :notice => 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  
  def update_cover_photo
    @project = Project.find(params[:id])
    @project.cover_photo = Photo.new
    @project.cover_photo.create_photo(
      :uploaded_file => params[:project][:cover_photo],
      :name => "project_#{@project.id}_cover_photo",
      "thumbnail_width_large" => Settings.project_cover_photo_width,
      "thumbnail_height_large" => Settings.project_cover_photo_height
      )
      
    if @project.save
      respond_to_ajax(:encapsulate => params.delete(:encapsulate), :target => "#project_#{@project.id}_cover_photo", :html => "<img src='#{@project.cover_photo.thumbnail_url}'>", :track_history => false)
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :sub_title %><br />
    <%= f.text_field :sub_title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :detail %><br />
    <%= f.text_field :detail %>
  </div>
  <div class="field">
    <%= f.label :project_type %><br />
    <%= f.select :project_type, ProjectType.collect {|k, v| [k, v]} %>
  </div>
  <div class="field">
    <%= f.label :project_content_type %><br />
    <%= f.select :project_content_type, ProjectContentType.collect {|k, v| [k, v]} %>
  </div>
  <div class="field">
    <%= f.label :content_html %><br />
    <%= f.text_field :content_html %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_index.html.erb
<% content_for :content_main do %>
  <div class="projects">
    <div class="index">
      <% for i in 0...[((@projects.length - 1) / 4) + 1, 3].max %>
        <div class="project_row <%= "first" if i == 0 %>">
          <% for j in 0...4 %>
            <% project_index = i * 4 + j %>
            <% if project_index < @projects.length %>
              <% project = @projects[project_index] %>
              <div class="project <%= "last" if j == 3 %>">
                <%= form_for project, :method => :get, :remote => true, :html => { :class => "form_project" } do %>
                  <a class="link_project scroll_to_top">
                    <div id="project_<%= project.id %>_cover_photo" class="cover_photo">
                      <%= image_tag project.cover_photo.thumbnail_url(:thumbnail_size => :large) if !project.cover_photo.nil? %>
                    </div>
                    <div class="project_content">
                      <div class="title"><%= project.title %></div>
                      <div class="separator"></div>
                      <div class="sub_title"><%= project.sub_title.html_safe %></div>
                    </div>
                  </a>
                <% end %>
                <% if admin_signed_in? %>
                  <%= form_for project, :url => "/projects/#{project.id}/update_cover_photo", :remote => true, :html => { :class => "form_update_cover_photo" } do |f| %>
                    <span class="inputFileContainer">
                      <span class="icon iconAddCream"></span>
                      <%= f.file_field(:cover_photo, :class => "autoSubmit") %>
                    </span>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <% if admin_signed_in? %>
    <h1>Listing projects</h1>

    <table>
      <tr>
        <th>title </th>
        <th>sub_title</th>
        <th>description</th>
        <th>detail</th>
        <th>project_type</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.sub_title %></td>
        <td><%= project.description %></td>
        <td><%= project.detail %></td>
        <td><%= project.project_type %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
    </table>
    <br />
    <%= link_to 'New Project', new_project_path %>
  <% end %>
<% end %>
<% render :partial => "shared/empty_project_stage" %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= render :partial => "projects/index" %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% content_for :project_stage do %>
  <% $html_actions[:project_stage] = "replace_slow" %>
  <div class="projects">
    <div class="show">
      <div class="project_id" value="<%= @project.id %>" style="display: none;"></div>
      <div class="project_description">
        <div class="title"><%= @project.title %></div>
        <div class="title_separator"></div>
        <div class="sub_title"><%= @project.sub_title.html_safe %></div>
        <div class="description"><%= @project.description.html_safe %></div>
        <div class="description_separator"></div>
        <div class="detail"><%= @project.detail.html_safe %></div>
      </div>
      <div class="project_presentation">
        <% case @project.project_content_type %>
        <% when Settings.project_content_type_photos %>
          <div class="data_photos" style="display: none;" photo_count="<%= @project.photos.length %>"> >
            <% @project.photos.each_with_index do |photo, index| %>
              <div class="<%= index %>" photo_url="<%= photo.thumbnail_url_small %>"></div>
            <% end %>
          </div>
          <div class="image_presentation">
            <div class="image_container">
              <%= image_tag @project.photos[0].thumbnail_url_small if @project.photos.length > 0 %>
            </div>
          </div>
          <a class="button_nav prev nav_end" index="-1"><</a>
          <a class="button_nav next <%= "nav_end" if @project.photos.length <= 1 %>" index="1">></a>
        <% when Settings.project_content_type_html %>
          <%=raw @project.content_html %>
        <% end %>
      </div>
    </div>
    <% if admin_signed_in? %>
      <% @imageable = @project %>
      <%= render :template => "photos/index" %>
    <% end %>
  </div>
<% end %>