config/routes.rb
Sebitmin::Application.routes.draw do
  devise_for :admins
  resources :photos
  
  match "projects/:id/update_cover_photo" => "projects#update_cover_photo"
  resources :projects do
    resources :photos
  end

  root :to => 'projects#index'
  get "info/about_me"

end

app/models/photo.rb
require 'RMagick'

class Photo < ActiveRecord::Base
  include Controllers::AwsHelper
  include Magick
  
  belongs_to :imageable, :polymorphic => true

  def create_photo(args = {})
    if args.key?(:uploaded_file)
      uploaded_file = args[:uploaded_file]
      ext = File.extname(uploaded_file.original_filename)
      org_file = uploaded_file.tempfile
    elsif args.key?(:url)
      url = args[:url]
      ext = File.extname(url)
      org_file = open(url)
    else
      throw "Usage: create_photo(:uploaded_file => $(uploaded_file)) or create_photo(:url => $(url))"
    end
    
    if args.key?(:name)
      name = args[:name]
    else
      name = "photo_#{self.id}"
    end
    
    # Org file
    #f = Tempfile.new([name, ext], Rails.root.join('tmp'), :encoding => 'ascii-8bit')
    f = Tempfile.new([name, ext], Rails.root.join('tmp'))
    begin
      f << org_file.read
    ensure
      f.close
    end
    s3_object = aws_s3_upload(f.path)

    self.url = s3_object.public_url.to_s
    self.key = s3_object.key
    
    Sebitmin::Application.config.thumbnail_sizes.each do |thumbnail_size|
      create_thumbnail(f, thumbnail_size, args)
    end
    
    result = self.save

    f.unlink
    
    result
  end
  
  def create_thumbnail(org_file, thumbnail_size, args = {})
    ext = File.extname(org_file.path)
    thumbnail_width_sym = "thumbnail_width_#{thumbnail_size}"
    if args.key?(thumbnail_width_sym)
      thumbnail_width = args[thumbnail_width_sym].to_f
    else
      thumbnail_width = Settings[thumbnail_width_sym].to_f
    end
  
    thumbnail_height_sym = "thumbnail_height_#{thumbnail_size}"
    if args.key?(thumbnail_height_sym)
      thumbnail_height = args[thumbnail_height_sym].to_f
    else
      thumbnail_height = Settings[thumbnail_height_sym].to_f
    end
  
    img = Magick::Image.read(org_file.path).first
    if img.columns > thumbnail_width or img.rows > thumbnail_height
      org_width = img.columns.to_f
      org_height = img.rows.to_f
      
      width_scale = thumbnail_width.to_f / org_width
      height_scale = thumbnail_height.to_f / org_height
    
      if width_scale > height_scale
        scale = width_scale
      else
        scale = height_scale
      end
      
      if scale > 1.0
        scale = 1.0
      elsif scale < 1.0
        img = img.scale(scale)
      end
      
      img.background_color = "#00000000"
      img = img.extent(thumbnail_width, thumbnail_height, (org_width * scale - thumbnail_width) * 0.5, (org_height * scale - thumbnail_height) * 0.5)
    end
  
    #thumbnail = Tempfile.new(["photo_#{self.id}_thumbnail_#{thumbnail_size}", ext], Rails.root.join('tmp'), :encoding => 'ascii-8bit')
    thumbnail = Tempfile.new(["photo_#{self.id}_thumbnail_#{thumbnail_size}", ext], Rails.root.join('tmp'))
    begin
      thumbnail << img.to_blob
    ensure
      thumbnail.close
    end
    s3_object_thumbnail = aws_s3_upload(thumbnail.path)
    
    self["thumbnail_url_#{thumbnail_size}"] = s3_object_thumbnail.public_url.to_s
    key_field = "thumbnail_key_#{thumbnail_size}"
    if !self[key_field].nil?
      aws_s3_delete(self[key_field])
    end
    self[key_field] = s3_object_thumbnail.key

    thumbnail.unlink
  end
  
  def thumbnail_url(args = {})
    size = args.delete(:thumbnail_size) || :small
    case size
    when :small
      self.thumbnail_url_small
    else
      self.url
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  include Controllers::AwsHelper
  before_filter :authenticate_admin!
  
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])
    
    create_photo_args = {}
    create_photo_args[:uploaded_file] = params[:photo_url]
    
    Sebitmin::Application.config.thumbnail_sizes.each do |thumbnail_size|
      thumbnail_width_sym = "thumbnail_width_#{thumbnail_size}"
      if params.key?(thumbnail_width_sym)
        create_photo_args[thumbnail_width_sym] = params[thumbnail_width_sym]
      end
      
      thumbnail_height_sym = "thumbnail_height_#{thumbnail_size}"
      if params.key?(thumbnail_height_sym)
        create_photo_args[thumbnail_height_sym] = params[thumbnail_height_sym]
      end
    end
    @photo.create_photo(create_photo_args)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, :notice => 'Photo was successfully created.' }
        format.json { render :json => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, :notice => 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])

    # Destroy s3 objects
    aws_s3_delete(@photo.key)
    Sebitmin::Application.config.thumbnail_sizes.each do |thumbnail_size|
      aws_s3_delete(@photo["thumbnail_key_#{thumbnail_size}"])
    end

    @photo.destroy

    respond_to do |format|
      format.html { redirect_to "/" }
      format.json { head :no_content }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo, :html => {:multipart => true}) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= file_field_tag(:photo_url) %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <%= f.hidden_field :imageable_type, :value => params[:imageable_type] %>
  <%= f.hidden_field :imageable_id, :value => params[:imageable_id] %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Key</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @imageable.photos.each do |photo| %>
  <tr>
    <td><%= photo.url %></td>
    <td><%= photo.key %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', "/photos/new?imageable_type=#{@imageable.class.to_s}&imageable_id=#{@imageable.id}" %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @photo.url %>
</p>

<p>
  <b>Key:</b>
  <%= @photo.key %>
</p>
<p>
  <b>Org:</b>
  <%= image_tag @photo.url %>
</p>
<% Sebitmin::Application.config.thumbnail_sizes.each do |thumbnail_size| %>
  <p>
    <b><%= thumbnail_size.to_s %></b>
    <%= image_tag @photo["thumbnail_url_#{thumbnail_size}"] %>
  </p>
<% end %>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>